### ISSUE TITLE
player_yaw placeholder flickering

### ISSUE THREAD

**Issue by Mataaaaaaaa** [NEZNAMY/TAB#1065]
### Server version

Purpur 1.20.1

### TAB version

4.0.3

### Describe the bug

When using %player_yaw% placeholder in bossbar as a display condition, it causes the text of the bossbar to flicker (quickly disappearing and appearing again in quick succession) as I move the mouse around and change the placeholders value creating an unpleasant looking effect. Oddly enough the flickering sometimes stops almost completely and starts again only after using /tab reload (even if no configuration has been changed since then)

### Expected behavior

I would expect the bossbar text not to flicker and instead immediately display the correct text according to display conditon.

### Steps to reproduce

Step 1: Download PAPI and PAPI Player extension

Step 2: enable the bossbar feature and add the following configuration:

```yml
bars:
    hodiny:
      style: PROGRESS
      color: 'WHITE'
      progress: '100'
      text: '&a■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■'
    kompas2:
      style: PROGRESS
      color: 'WHITE'
      progress: '100'
      text: '&c■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■'
      display-condition: "%player_yaw%>0"
```

Step 3: Decrease the refresh interval of `%player_yaw%` placeholder in TABs config, this makes the flickering much more apparent, I personally set it down all the way down to 50.

Step 4: Upon reloading the plugin, the text in bossbar should flicker sometimes, especially when the value of player yaw exceeds 0 making the other bossbar visible.

Although this should make it clear what the issue is and be enough to reproduce it, it might not make the problem look apparent enough. If thats the case, please proceed to further steps which basically show my actual configuration.

Step 5: Download Utils and Math PAPI extensions.

Step 6: add the following configuration to the plugin, I used a paste site as it is quite long: https://pastes.dev/KHmHPFgElo

Step 7: decrease refresh interval of this placeholder: `%utils_parse_math_0_{math_0_{player_yaw}/5}*5%` (makes the flickering more apparent)

### Additional info
The other bossbar made of just static text with no display conditions is there to show that it flickers as well which I personally find quite weird.

I get that this may be a general limitation either of how placeholders work, of how TAB refreshes placeholder or of my configuration as most people probably dont usually use TAB to make a HUD (a compass in my case). If this can be solved somehow, it would be really cool. If not, sorry for wasting your time.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
