### ISSUE TITLE
Nametag lag behind intended location.

### ISSUE THREAD

**Issue by lafless** [NEZNAMY/TAB#1118]
### Server version

Paper 1.20.1

### TAB version

4.0.7

### Describe the bug

The nametags seem to lag behind players and have a bezier effect when moving. It is smooth, but not intended.

### Expected behavior

The nametags should stay about the player's head as presented in vanilla Minecraft.

### Steps to reproduce

Step 1: Set `unlimited-nametag-mode` to `true`

Step 2: Create three dynamic lines in `config.yml`
```
  unlimited-nametag-mode:
    enabled: true
    disable-on-boats: false
    disable-condition: '%world%=disabledworld'
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    static-lines:
      myCustomLine: 0.66
```

Step 3: Define those lines in `groups.yml`, here's the example I used.
```
_DEFAULT_:
  tabprefix: "%luckperms-prefix%"
  tagprefix: ""
  tabsuffix: "%luckperms-suffix%"
  abovename: "%luckperms-prefix%%luckperms_highest_group_by_weight%"
  belowname: "&f%level%"
  tabsuffix: "    "
Default:
  tabprefix: "%luckperms-prefix%"
  tagprefix: ""
  tabsuffix: "%luckperms-suffix%"
  abovename: ""
  belowname: "&f%level%"
  tabsuffix: "    "
```

Have an alt account or friend run around and view the behavior of the nametag.

### Additional steps

If you cannot reproduce with the steps above, alter tab layout to see if it is a factor:
```
layout:
  enabled: true
  direction: COLUMNS
  default-skin: texture:0
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      groups:
        players:
          slots:
          - 1-80
```

### Additional info

I appreciate anyone who has put time into this project. I have seen the recent mentions of it being on its last straw. I know that several people will be willing to use it even if is a premium-only resource, and we will be forever grateful if it continues. Thanks for working on it and I hope everything goes well for anyone reading this.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
