### ISSUE TITLE
Nametag of player does not get colored correctly

### ISSUE THREAD

**Issue by TheJoshue** [NEZNAMY/TAB#1183]
### Server version

1.12.2

### TAB version

4.1.2

### Describe the bug

Nametag coloring acting weird
It does work correctly and is corresponding to %luckperms_prefix% placeholder
![image](https://github.com/NEZNAMY/TAB/assets/56804505/d65309ea-66de-4d28-9cd0-2fe2664db07d)

### Expected behavior

Should be the same on tablist and nametag too, it is exactly same prefix
i am using default config for groups:
```yml
#Owner:
#  tabprefix: "&0&l[&a&lOwner&0&l] &a"
#  tagprefix: "&2&lOwner &a"
Player:
  tabprefix: "&0&l[&7&lPlayer&0&l] &3"
  tagprefix: "&2&lPlayer &3"
example_group:
  header:
    - "This is an example of per-group header/footer"
  footer:
    - "applied to a group"

 # default settings for all groups, all groups will take properties from this section unless player's primary group overrides a specific setting
_DEFAULT_:
  tabprefix: "%luckperms-prefix%"
  tagprefix: "%luckperms-prefix%"
  customtabname: "%player%"
  customtagname: "%player%" # don't forget to enable unlimited nametag mode to make this one work
  tabsuffix: "%luckperms-suffix%"
  tagsuffix: "%luckperms-suffix%"

per-world:
  world1:
    Owner:
      tabprefix: "&0&l[&a&lOwner&0&l] &a"
      tagprefix: "&2&lOwner &a"
```
and for users too:
```yml
_NEZNAMY_:
  tabprefix: "&6&lTAB&r &a"
  tagprefix: "&6&lTAB&r &a"
  abovename: "&bOh look, 3 lines of text !"
  belowname: "&eThere's only one plugin out there supporting it"
237d8b55-3f97-4749-aa60-e9fe97b45062: # my online uuid
  tabsuffix: " &b&lVerified"
```

### Steps to reproduce

1. Set prefix via luckperms to player or give them `prefix.1000.&8[&4&oAdmin&8] &4` (that is exactly what i used)
2. Check to see if it works on tablist with default tab configuration files; check ot see if it works for nametag above mc character

### Additional info

i am not using any plugin that conflicts with nametags, tab is the only one

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds
