### ISSUE TITLE
PAPI placeholder not parsed

### ISSUE THREAD

**Issue by ChemFlix** [NEZNAMY/TAB#1207]
### TAB version

4.1.2

### Software causing compatibility issue

PlaceholderAPI-2.11.5

### Additional info

![2024-01-11_06 38 06](https://github.com/NEZNAMY/TAB/assets/114338506/a0c91a06-b479-4b14-9844-496f5ee5a428)

in groups.yml:
```
_DEFAULT_:
  tabprefix: '%vault-prefix%'
  tagprefix: '%vault-prefix%'
  tabsuffix: '%parseother_{player_name}_{changeoutput_contains_input:{essentials_afk}_matcher:yes_ifmatch: &7*&7&lAFK&7*_else:}%'
  tagsuffix: '%parseother_{player_name}_{changeoutput_contains_input:{essentials_afk}_matcher:yes_ifmatch: &7*&7&lAFK&7*_else:}%'
  customtabname: '%essentials_nickname%'
  customtagname: '%essentials_nickname%'
  abovename: '%vault-prefix%'
```

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds
