### ISSUE TITLE
[Velocity] Minimessage hex-colors displaying as legacy colors

### ISSUE THREAD

**Issue by Lion-King287** [NEZNAMY/TAB#1256]
### Server version

Velocity 3.3.0 / Paper 1.20.4

### TAB version

4.1.2 (+ brige on subservers)

### Describe the bug

If you use minimessage hex-codes in the tablist or in the nametag (tablist) it will be converted to normal minecraft-colors.
![image](https://github.com/NEZNAMY/TAB/assets/74682634/417c986f-fea9-42ef-93d4-1113b9066046)
![image](https://github.com/NEZNAMY/TAB/assets/74682634/0f85b0a5-f9b3-4ccd-ac19-44c59bf2f162)

### Expected behavior

It should display the hex-codes normally.

### Steps to reproduce

1. Use mini-message hex-codes in the tablist
2. Check the tablist ingame

### Additional info

```yml
header-footer:
  enabled: true
  header:
  - <rainbow><st>                                                </st></rainbow>
  - '<aqua><bold>LOCOBROKO.NET NETZWERK</bold>'
  - '<gray>Es sind <white>%online% <gray>Spieler online.'
  - ''
  footer:
  - ''
  - '<gray>Hostey by <aqua>tube-hosting.com'
  - <rainbow><st>                                                </st></rainbow>
```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds
