### ISSUE TITLE
legacy hex format seems not to be working and changes to the non hex legacy color format of the ranks

### ISSUE THREAD

**Issue by Melon-Oof** [NEZNAMY/TAB#1259]
### Server version

Paper 1.20.4 b.459

### TAB version

3.1.3 SNAPSHOT (commit b14b682)

### Describe the bug

I've used different color formats, &x&r&r&g&g&b&b or &#rrggbb for my luckperms prefixes. When the server first starts and loads successfully, The hex shows up but if I change my luckperms group or reload TAB the color shifts to it's closest [non hex color](https://htmlcolorcodes.com/minecraft-color-codes/) example would be &x&f&f&0&0&0&0 shifts to &4.

### Expected behavior

Have the plugin to use the chosen HEX color insead of its closest non hex on reload or group change

### Steps to reproduce

1. Use Paper 1.20.4 build 459 (or another 1.20.4 build)
2. Latest TAB Dev Build, LuckPerms 5.4.121
3. Create 2 group with the formats I mentioned prveiously (&x&r&r&g&g&b&b or &#rrggbb)
4. change group or reload TAB

### Additional info

There is no minimessage and legacy format mixed. 

My plugin list:
- *AntiWorldDownloader, AxKills, ChatSentinel, Citizens, CommandWhitelist, DecentHolograms, DeluxeMenus, Essentials, EssentialsSpawn, FastAsyncWorldEdit
FasterCrystals, FreedomChat, GrimAC, LPC, LuckPerms, Multiverse-Core, PlaceholderAPI, ProJumpPads, ProtocolLib, StrikeKitsRegen
*StrikePractice, *StrikeSurrender, TAB, *TitleStrikePractice, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldGuard

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Try defining the prefix directly in groups.yml. If it's still broken, send the file that doesn't work properly.

**Comment by Melon-Oof** [comment]
![Screenshot 2024-03-30 153621](https://github.com/NEZNAMY/TAB/assets/147187344/e2018f12-fa6c-4864-87c5-8942e6ec7268)

```
_DEFAULT_:
  tabprefix: "&#ff0000 "
  tagprefix: "&#ff0000 "
  tabsuffix: "%luckperms_suffix%"    
  tagsuffix: "%luckperms_suffix%"
owner:
  tabprefix: "&#ff0000&lOWNER &f&l"
  tagprefix: "&#ff0000 &f&l"
  tabsuffix: "%luckperms_suffix%"    
  tagsuffix: "%luckperms_suffix%"
mod:
  tabprefix: "&7[&9ᴍᴏᴅ&7] &x&f&f&0&0&0&0"
  tagprefix: "&7[&9ᴍᴏᴅ&7] &x&f&f&0&0&0&0"
  tabsuffix: "%luckperms_suffix%"    
  tagsuffix: "%luckperms_suffix%"
ace:
  tabprefix: "&x&f&f&a&f&0&a&lACE &x&f&f&0&0&0&0"
  tagprefix: "&x&f&f&a&f&0&a&lACE &x&f&f&0&0&0&0"
  tabsuffix: "%luckperms_suffix%"    
  tagsuffix: "%luckperms_suffix%"
champion:
  tabprefix: "&x&1&d&0&b&9&6&lCHAMPION &x&f&f&0&0&0&0"
  tagprefix: "&x&1&d&0&b&9&6&lCHAMPION &x&f&f&0&0&0&0"
  tabsuffix: "%luckperms_suffix%"    
  tagsuffix: "%luckperms_suffix%"
immortal:
  tabprefix: "&6&lIMMORTAL &x&f&f&0&0&0&0"
  tagprefix: "&6&lIMMORTAL &x&f&f&0&0&0&0"
  tabsuffix: "%luckperms_suffix%"    
  tagsuffix: "%luckperms_suffix%"
deadliest:
  tabprefix: "&x&1&e&6&0&d&9&lDEADLIEST &x&f&f&0&0&0&0"
  tagprefix: "&x&1&e&6&0&d&9&lDEADLIEST &x&f&f&0&0&0&0"
  tabsuffix: "%luckperms_suffix%"    
  tagsuffix: "%luckperms_suffix%"
elite:
  tabprefix: "&b&lELITE &x&f&f&0&0&0&0"
  tagprefix: "&b&lELITE &x&f&f&0&0&0&0"
  tabsuffix: "%luckperms_suffix%"    
  tagsuffix: "%luckperms_suffix%"
```

This group.yml would work with the groups in the screenshot attached correct?
