### ISSUE TITLE
Scoreboard display condition for %world% not working properly

### ISSUE THREAD

**Issue by Pyario** [NEZNAMY/TAB#1336]
### Server version

1.21

### TAB version

4.1.6

### Plugin list

As in the title I have the following display condition:

```
  scoreboards:
    scoreboard_3:
      disable-condition: '%world%=world'
      title: §c§lBaustuebchen.de §8§l| §5§lSpawn
      lines:
      - '&e&m============================='
      - ' '
      - ' &6&lSpieler&8&l-&c&lInformationen&8&l:'
      - ' '
      - ' §8§l➥ &7Money&8: &a%lighteconomy_money% &6Gems'
      - ' §8§l➥ &7Rang&8: &a%PJ_PREFIX%%player_name%'
      - ' §8§l➥ &7Votepunkte&8: %VS_POINTS%'
      - ' §8§l➥ &7Votes&8: %VS_VOTES%'
      - ' §8§l➥ &7Spielzeit&8: %playtime_time%'
      - ' '
      - '&e&m============================='
    scoreboard_2:
      disable-condition: '%world%=chunks'
      title: §c§lBaustuebchen.de §8§l| §e§lBauwelt
      lines:
      - '&e&m============================='
      - ' '
      - ' &6&lSpieler&8&l-&c&lInformationen&8&l:'
      - ' '
      - ' §8§l➥ &7Money&8: &a%lighteconomy_money% &6Gems'
      - ' §8§l➥ &7Rang&8: &a%PJ_PREFIX%%player_name%'
      - ' §8§l➥ &7Spielzeit&8: %playtime_time%'
      - ''
      - ' &6&lChunk&8&l-&c&lInformationen&8&l:'
      - ' '
      - ' §8§l➥ &7Owner&8: %CS_OWNER%'
      - ' §8§l➥ &7Anzahl&8: %CS_HAS%'
      - ' '
      - '&e&m============================='
```

### Describe the bug

I see the scoreboard scoreboard_3 in both worlds, "world" and "chunks". And it's not a typo. Even via /tab parse me %world% is the output "chunks" as a world. So what's wrong with that? In 1.20.4/6 it didn't always work sometimes even though the wiki says I should do it that way... But since 1.21 it somehow doesn't work.

### Expected behavior

Everything loads but the scoreboards are not displayed correctly.

### Steps to reproduce

Configuire tow Scoreboards with different worlds..

### Additional info

![image](https://github.com/user-attachments/assets/7910d5a2-4850-4ac6-9c99-968b2c4450c3)
![image](https://github.com/user-attachments/assets/d3c66ba4-98cf-4b13-8397-2a86da9b164b)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds
