### ISSUE TITLE
There is a extra name in the tablist (Resolved)

### ISSUE THREAD

**Issue by scriptnapps** [NEZNAMY/TAB#1344]
### Server version

1.21 and 1.8

### TAB version

4.1.6

### Plugin list

floodgate-velocity.jar	
Geyser-Velocity.jar	
KickRedirect-2.0.10.jar	
LuckPerms-Velocity-5.4.137.jar	
TAB.v4.1.6.jar	

### Describe the bug

when i make a layout the fixet number 1 gets to be number 2 (it adds myself in a new number 1 spot)

### Expected behavior

not show myself (outside the layout) 

### Steps to reproduce

```
layout:
  enabled: true
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - 1|&2&lLobby
      - 21|&2&lSaphir
      - 41|&2&lDiamant
      - 61|&2&lEvent
      groups:
        llobby:
          condition: '%server%=lobby'
          slots:
          - 2-20
        ssaphir:
          condition: '%server%=pvplegacy'
          slots:
          - 22-40
        ddiamond:
          condition: '%server%=survival'
          slots:
          - 42-60
        eevent:
          condition: '%server%=event'
          slots:
          - 62-80 
```

### Additional info

it added my self without any markup in the first spot (0) 

![image](https://github.com/user-attachments/assets/eac35303-4bf8-46d4-bcad-fe32ed1875b6)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

EDIT:

you just need https://github.com/NEZNAMY/TAB/wiki/TAB-Bridge#:~:text=Encodes%20scoreboard%20packets%20(if%20TAB%20is%20installed%20on%20Velocity%2C%20which%20doesn%27t%20offer%20them) on the backend
