### ISSUE TITLE
Conditional Result Determination

### ISSUE THREAD

**Issue by Maplesaki** [NEZNAMY/TAB#1375]
### Server version

Velocity-3.3.0&Paper1.20.1&Paper1.21.1

### TAB version

4.1.6

### Plugin list

Velocity-3.3.0
　TAB v4.1.6

Paper1.20.1
　CMI-9.7.6
　TAB-Bridge v5.0.7
　PlaceholderAPI-2.11.6

Paper1.21.1
　EssentialsX-2.21.0
　TAB-Bridge v5.0.7
　PlaceholderAPI-2.11.6

### Describe the bug

If the CMI plugin is not installed, the result for %cmi_user_nickname% will be the player's name, not %cmi_user_nickname%.
```
conditions:
  nick:
    conditions:
      - "%player%=%cmi_user_nickname%"
      - "%cmi_user_nickname%='%cmi_user_nickname%'"
    type: OR
    yes: "%player%"
    no: "%cmi_user_nickname%"
```

![2024-10-27_15 47 31](https://github.com/user-attachments/assets/793bada3-b487-4c66-a164-6bcc7d8d5f17)

### Expected behavior

I want the following behavior:
- If neither CMI nor ESS is installed, return the player's raw name.
- If CMI is installed, return %cmi_user_nickname%.
- If ESS is installed, return %essentials_nickname%

```
conditions:
  nick_check:
    conditions:
      - "%player%=%cmi_user_nickname%"
      - "%player%=%essentials_nickname%"
    type: OR
    yes: "%player%"
    no: "%condition:nick_cmi_or_ess%"
  nick_cmi_or_ess:
    conditions:
      - "%player%!=%cmi_user_nickname%"
    yes: "%cmi_user_nickname%"
    no: "%essentials_nickname%"
```

### Steps to reproduce

Describe and Expected code

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Placeholders are parsed in both sides of the condition, so checking if placeholder equals itself doesn't make sense. Either use [per-server settings](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Tablist-name-formatting#per-world--per-server) and only set the placeholder in that server(s), or use [replacements](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements) and replace identifier itself to %player% for example. What is the bug here exactly? And on which marketplace is 4.1.6 latest?

**Comment by Maplesaki** [comment]
The expression "%cmi_user_nickname%='%cmi_user_nickname%'" is not two placeholders; it returns the text "%cmi_user_nickname%" as shown in the image above because the plugin is not installed. I prefer not to use per-server settings since there are too many servers to configure. I hope to resolve this directly using conditions. I apologize for not confirming that the version is the latest.

<img width="1324" alt="2024-10-27_15 47 31" src="https://github.com/user-attachments/assets/056c0c54-30a7-4541-9540-6906b305eff8">

**Comment by NEZNAMY** [comment]
The expression checks if placeholder is equal to itself, well, except you added extra `'`, so it never evaluates to `true`. You can achieve your goal with replacements, replace identifier to %player%, for example:
```
placeholder-output-replacements:
  "%cmi_user_nickname%":
    "%cmi_user_nickname%": "%player%"
```
Here, placeholders are not parsed on the left side, allowing you to achieve your goal. I still don't see any bug here.

**Comment by Maplesaki** [comment]
Solved! Thank you for your trouble.

```
placeholder-output-replacements:
  '%cmi_user_nickname%':
    '%cmi_user_nickname%': "%player%"
  '%essentials_nickname%':
    '%essentials_nickname%': "%player%"
conditions:
  nick:
    conditions:
      - "%player%=%cmi_user_nickname%"
      - "%player%=%essentials_nickname%"
    type: AND
    yes: "%player%"
    no: "%condition:nick_cmi_or_ess%"
  nick_cmi_or_ess:
    conditions:
      - "%player%!=%cmi_user_nickname%"
    yes: "%cmi_user_nickname%"
    no: "%essentials_nickname%"
```
![2024-10-27_18 19 54](https://github.com/user-attachments/assets/7b6443e6-862d-4003-b945-09d24a204c6c)
