### ISSUE TITLE
Is MiniMessage supported in groups' customtabname?

### ISSUE THREAD

**Issue by kangarko** [NEZNAMY/TAB#1408]
### TAB version

5.0.3

### Software causing compatibility issue

Using ChatControl.

In groups.yml under _DEFAULT_.customtabname I am using my plugin's nick which returns a minimessage tag such as `<gradient:red:blue>ahojky`

Result:

![a](https://i.imgur.com/IPkFnws.png)

Converting minimessage to section such as `§ca§x§d§d§5§5§7§7h§x§b§b§5§5§9§9o§x§9§9§5§5§b§bj§x§7§7§5§5§d§dk§9y` works fine.

Works fine:

![a](https://i.imgur.com/gQAieNX.png)

My question is since EternalTags works fine, I am doing something wrong in the plugin or is simply parsing minimessage tags unsupported and we need to be resorting to this crazy §x formatting?

Thanks.
Matej

### Checklist

- [X] I am running latest version of the plugin
- [ ] I ticked all of the boxes without actually reading them
- [X] The compatibility wiki page does not mention this incompatibility
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by kangarko** [comment]
Note: Whats strange is that when I return `<#ccffdd>` or any other hex in the mini format in the variable it works fine.

**Comment by Tanguygab** [comment]
Most likely linked to this
https://github.com/NEZNAMY/TAB/wiki/Frequently-Asked-Questions#16---is-minimessage-supported
![image](https://github.com/user-attachments/assets/501a1a66-6dcd-4a22-95db-c79d9920181c)

**Comment by kangarko** [comment]
I don't think so, because I am not combining those. My nick is literally `<gradient:blue:red>test`

**Comment by Tanguygab** [comment]
what about your tabprefix & tabsuffix?

**Comment by kangarko** [comment]
Same behavior. I needed to convert the gradient to §x in order for it to work.

**Comment by Tanguygab** [comment]
that's not what I meant, what are you using in your tabprefix & tabsuffix? If you're using legacy & colors in there, it'll break MiniMessage syntax even if it's in customtabname (when sent to the client, all 3 properties are merged into 1)

**Comment by kangarko** [comment]
Oh I see. I am just using my placeholder which gives the minimessage tag:

```yaml
_DEFAULT_:
  tabprefix: "%chatcontrol_player_prefix_section% "  
  tagprefix: "%eternaltags_tag_formatted%"
  customtabname: "%chatcontrol_player_nick_section%"
  tabsuffix: "%chatcontrol_player_suffix_section%"
  tagsuffix: "%luckperms-suffix%"
```
