### ISSUE TITLE
 Condition placeholder not getting parsed sometimes

### ISSUE THREAD

**Issue by TheZexquex** [NEZNAMY/TAB#1416]
### Server version

Paper 1.21.4 / Velocity 3.4.0-SNAPSHOT

### TAB version

TAB 5.0.3 / TAB-Bridge 6.0.1

### Plugin list

![grafik](https://github.com/user-attachments/assets/1d48d77e-0e85-41d9-8314-29bed6d41cdb)

### Describe the bug

Conditional Placeholders (or at least one of them) to at some point stop working / being parsed. This only started happening after upgrading from TAB 4.x to 5.x (and Bridge 5.x to 6.x)

It is the case for the internal placeholder (`%condition:xxxxxx%`) as well as for the external placeholder (`%tab_placeholder_condition:xxxxxxx%`) It seems to happen when another placeholder (that is also used in the tab name or name tag) is changed. At least that is what I think is happening.

### Expected behavior

The placeholder should be parse at any time.

### Steps to reproduce

Setup a Paper Server with Luckperms, PAPI and TAB-Bridge
Setup a Velocity Proxy with TAB, Velocity Scoreboard API

Create a conditional placeholder (In my case it checks a LuckPerms meta entry and uses another Luckperms meta entry as output)
Use the conditional placeholder and a placeholder that changes over time (in my test setup its the players death statistic `%statistic_deaths%`) in the tab / tag prefix or in the tab name. Once the normal placeholder updates, the conditional placeholder no longer gets parsed.

My groups..yml https://haste.devcord.club/ruvokaneye.pl
My config.yml https://haste.devcord.club/tavodaxasu.coffeescript
My animations.yml https://haste.devcord.club/averirokok.sql

### Additional info

https://github.com/user-attachments/assets/f9f8a474-75d6-444e-8341-37ede1376f06

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by TheZexquex** [comment]
(Ignore the second broken tab entry, that server is just not up to date)

**Comment by NEZNAMY** [comment]
I need the steps to reproduce.

**Comment by TheZexquex** [comment]
I just set up a minimal test scenario and can reproduce without any of the plugins listed above.
Added steps to reproduce

**Comment by NEZNAMY** [comment]
Try latest build from actions.

**Comment by TheZexquex** [comment]
Still doesn't work with TAB-5.0.4-SNAPSHOT+1464 :/ 
I noticed that rejoining seems to fix the placeholder parsing again.
So placeholder works -> other placeholder gets updated ->placeholder doesn't work anymore -> rejoin -> placeholder works again.
Also, only some conditional placeholders seem to be affected.
%condition:online%
```
  online:
    conditions:
    - '%online%=1'
    true: <gray>Derzeit ist <yellow>%online% <gray>Spieler online
    false: <gray>Derzeit sind <yellow>%online% <gray>Spieler online
```
for example works, but
%condition:prefix%
```
  prefix:
    conditions:
    - '%luckperms_meta_gender%=male'
    true: '%luckperms_meta_prefix-male%'
    false: '%condition:prefix2%'
  prefix2:
    conditions:
    - '%luckperms_meta_gender%=female'
    true: '%luckperms_meta_prefix-female%'
    false: '%luckperms_meta_prefix-diverse%'
```
does not.
