### ISSUE TITLE
Gradient color not working on TabList

### ISSUE THREAD

**Issue by Stabrinai** [NEZNAMY/TAB#1421]
### Server version

Folia 1.21.4

### TAB version

5.0.4

### Plugin list

Server Plugins (4):
Bukkit Plugins:
- LuckPerms, PlaceholderAPI, SkinsRestorer, TAB

### Describe the bug

```yaml
_DEFAULT_:
  tabprefix: "{#f2f542>}"
  tagprefix: "%luckperms-prefix%"
  customtabname: "%player%"
  tabsuffix: "{#4298f5<}"
  tagsuffix: "%luckperms-suffix%"

```

This won't work

![Image](https://github.com/user-attachments/assets/b6de9fd6-5199-401d-ac33-0c6845c1c217)

### Expected behavior

```yaml
_DEFAULT_:
  tabprefix: "{#f2f542>}"
  tagprefix: "%luckperms-prefix%"
  customtabname: "%player%"
  tabsuffix: "{#4298f5<}"
  tagsuffix: "%luckperms-suffix%"

```

This will work in version 5.0.3

![Image](https://github.com/user-attachments/assets/9955ff68-8fa0-4b24-8da6-78fe4f20cafa)

### Steps to reproduce

Use gradient color in tabList

### Checklist

- [x] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [x] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds
