### ISSUE TITLE
Minecraft formatting codes bug

### ISSUE THREAD

**Issue by mainulXD18** [NEZNAMY/TAB#1429]
### Server version

1.21.3 

### TAB version

5.0.6

### Plugin list

[12:18:25 INFO]: Paper Plugins:
[12:18:25 INFO]:  - FancyHolograms, FancyNpcs, HuskClaims, NookureStaff, RentIt, Typewriter
[12:18:25 INFO]: Bukkit Plugins:
[12:18:25 INFO]:  - AdvancedEnchantments, AdvancedModels, AdvancedRegionMarket, AdvancedSkills, AFKRewards, AlonsoLevels, AlonsoLib, AnimalsContest, AxInventoryRestore, AxiomPaper
[12:18:25 INFO]:  AxKills, AxKoth, AxTrade, BattlePass, BetterJails, BetterProfiles, BottledExp, chocofly, Chunky, CMILib
[12:18:25 INFO]:  CommandPrompter, ConditionalTextPlaceholders, ConsoleSpamFixReborn, CoreProtect, CustomFoods, DeluxeMenus, DisableMobAI, DiscordSRV, DiscordSRV-LinkChannel, DonutOrder
[12:18:25 INFO]:  DonutRTPzone, DupeProtect, DynamicShop, eGlow, Elevator, ExcellentCrates, FallbackServerAddon, FarmControl, FastAsyncWorldEdit, floodgate
[12:18:25 INFO]:  Flyblock, Geyser-Recipe-Fix, GSit, GUIHelper, HeadDatabase, HeadDisplays, InteractiveBooks, InvSeePlusPlus, ItemEdit, JoinEventsPro
[12:18:25 INFO]:  JSEngine, judge, LeaderboardMenus, LootChest, LPX, LuckPerms, MessageEditor, MetinEvent, MinerTrack, MiyukiDelivery
[12:18:25 INFO]:  MobFarmManager, Multiverse-Core, Multiverse-Inventories, MyCommand, NBTAPI, nightcore, NotBounties, *NotTooExpensive, packetevents, PassengerAPI
[12:18:25 INFO]:  Pl-Hide-Pro, PlaceholderAPI, PlayerKits2, PlayerVaults, *PlayTime, PlugManX, ProCosmetics, ProtocolLib, PurpurExtras, PvPManager
[12:18:25 INFO]:  Randomtp, RedisChat, ReferralDomains, RewardsLite, SafeNET, SellPlugin, ServerListPlus, ShiftHotkey, Shopkeepers, ShopkeepersAddon
[12:18:25 INFO]:  SkinsRestorer, Skript, sleep-most, SuperVanish, TAB, Topper, Tweakin, UltimateClans, UnlimitedNameTags, Vault
[12:18:25 INFO]:  Vehicles, ViaBackwards, ViaVersion, VillagerOptimizer, VotifierPlus, VotingPlugin, Vulcan, WelcomeRewards, WildChests, WorldGuard
[12:18:25 INFO]:  WorldGuardExtraFlags, zEssentials, zMenu, ZNPCsPlus

### Describe the bug

After updating to the newer version every &n (minecraft underline format) is formating into &m (minecraft strikethrough format).

### Expected behavior

&n should format the words with a underline. &m should format a word with a strikethrough.

### Steps to reproduce

anywhere in tab or scoreboard

- "&mthis should format this sentence with a strikethorugh"
- "&nthis should format this sentence with a underline"

### Checklist

- [x] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [x] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Zeronic76** [comment]
Hello.
I have the same problem.

I solved it by adding &r to the beginning of each line in the config.yml.

```
header:

- '&r&7Online players: &f%online%'

- '&r&6Online staff: &e%staffonline%'
```

**Comment by pgprimitz** [comment]
Still not fixed.

![Image](https://github.com/user-attachments/assets/dc8c7db4-6146-4093-a728-3df4c9b0abb3)

![Image](https://github.com/user-attachments/assets/350c8204-20c4-4a6e-8e05-ac29164e55b6)

**Comment by NEZNAMY** [comment]
> Still not fixed.
> 
> ![Image](https://github.com/user-attachments/assets/dc8c7db4-6146-4093-a728-3df4c9b0abb3)
> 
> ![Image](https://github.com/user-attachments/assets/350c8204-20c4-4a6e-8e05-ac29164e55b6)

Send your config. And just in case, output of `/ver tab` or `/tab debug` where we can see plugin version.

**Comment by thunder-red-star** [comment]
Tested it, having similar issues on the latest version. Additionally this affects obfuscated text as well.

Config:
```
header-footer:
  enabled: true
  header:
    - "&#FF0000&lLEGACY&r"
    - "&rthis should be &cOBFUSCATED&r: &ktest string"
    - "&rthis should be &6UNDERLINED&r: &ntest string"
    - "&rthis should be &eSTRIKETHROUGH&r: &mtest string"
    - ""
    - "&r&#FF0000&lMINIMESSAGE&r"
    - "<reset>this should be <red>OBFUSCATED: <reset><obf>test string"
    - "<reset>this should be <gold>UNDERLINED: <reset><u>test string"
    - "<reset>this should be <yellow>STRIKETHROUGH: <reset><st>test string"
  footer:
    - "<reset>tab is the <green>best <reset>plugin"
```

Plugins:
```
> plugins
[22:24:44 INFO]: Paper Plugins: (0):
[22:24:44 INFO]: Bukkit Plugins: (1):
[22:24:44 INFO]:  - TAB
```

Tab Info:
```
> tab debug
[22:21:21 INFO]: [TAB] [TAB] Showing debug information
[22:21:21 INFO]: [TAB] >-------------------------------<
[22:21:21 INFO]: [TAB] Server version: [Bukkit] Purpur - 1.21.4
[22:21:21 INFO]: [TAB] Plugin version: 5.0.6
[22:21:21 INFO]: [TAB] Permission plugin: None
[22:21:21 INFO]: [TAB] Permission group choice logic: Primary group
[22:21:21 INFO]: [TAB] Sorting system: GROUPS -> PLACEHOLDER_A_TO_Z
[22:21:21 INFO]: [TAB] Storage type: File
[22:21:21 INFO]: [TAB] >-------------------------------<
```

Result:

![Image](https://github.com/user-attachments/assets/e7cc4e81-113e-439b-a5d0-de67d80d9c0e)
