### ISSUE TITLE
Huge MSPT changes when players log in or out

### ISSUE THREAD

**Issue by RICE0707** [NEZNAMY/TAB#1462]
### Server version

waterfall 583 / PurPur 1.20.2

### TAB version

5.0.7 / TAB-Bridge 6.0.1

### Plugin list

Checked items
![Image](https://github.com/user-attachments/assets/e826e2e1-8475-4281-8b57-24445015853a)

### Describe the bug

https://github.com/user-attachments/assets/35ed6b25-767e-4b86-8565-8a3f078d39e7

### Expected behavior

MSPT should not have such a drastic change

### Steps to reproduce

I encountered this problem after upgrading directly from tab 4.1.8 to 5.0.7
Also, this issue was resolved when I removed the tab from bungee

### Checklist

- [x] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [x] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by RICE0707** [comment]
After testing,
I found that the` per-server: `of` header-footer: `was the root cause of this

**Comment by RICE0707** [comment]
After testing,
I found that `per-server:` of `header-footer:` was the root cause of this

When I set it to:
```yml
  per-server:
    第一分流;第二分流;第三分流;第四分流:
```
When players log in, they will have serious MSPT problems.
If set to
```yml
  per-server:
    第一分流:
```
The MSPT problem will be reduced, but it still exists.

If you completely remove this part of the settings, there will be no MSPT problem at all.
I think it has something to do with the number of players, that's just my guess

**Comment by RICE0707** [comment]
After testing, if `header: ` of `header-footer: ` contains placeholders,
There will be this MSPT problem,
When the same placeholder is used in ` footer: `, everything works fine.

Causing serious problems with MSPT:
```yml
header-footer:
  header:
  - '            &f/                                                      &f\            '
  - '        &7/                                                                &7\        '
  - '&f<                                                                          &f>'
  - '        &7\                                                                &7/        '
  - '            &f\                                                      &f/            '
  - '&fꆖꆗꆘ'
  - ''
  - '#cfffc0%serveronline% &8/ &f60 &8« &7%server% &8• &7全伺服 &8» #cfffc0%online% &8/ &f300'
  - ''
  footer:
  - ''
  - '#f6e0a4/menu &7開選單 &8- #f6e0a4/bs &7切分流 &8- #f6e0a4/sbt &7資訊欄 &8- #f6e0a4/discord&7加社群'
  - ''
```
Will not cause serious problems for MSPT:
```yml
header-footer:
  header:
  - '            &f/                                                      &f\            '
  - '        &7/                                                                &7\        '
  - '&f<                                                                          &f>'
  - '        &7\                                                                &7/        '
  - '            &f\                                                      &f/            '
  - '&fꆖꆗꆘ'
  - ''
  - ''
  footer:
  - ''
  - '#cfffc0%serveronline% &8/ &f60 &8« &7%server% &8• &7全伺服 &8» #cfffc0%online% &8/ &f300'
  - '#f6e0a4/menu &7開選單 &8- #f6e0a4/bs &7切分流 &8- #f6e0a4/sbt &7資訊欄 &8- #f6e0a4/discord&7加社群'
  - ''
```

**Comment by NEZNAMY** [comment]
Create a spark report and send it
`/spark profiler start --timeout 30 --thread * --interval 0.1`

**Comment by RICE0707** [comment]
> Create a spark report and send it `/spark profiler start --timeout 30 --thread * --interval 0.1`

https://spark.lucko.me/4zPllx90KP

**Comment by RICE0707** [comment]
> Create a spark report and send it `/spark profiler start --timeout 30 --thread * --interval 0.1`

https://spark.lucko.me/RMYXZsH7EZ

**Comment by RICE0707** [comment]
ERROR
```
26.03.2025 - 16:36:11 - [TAB v5.0.7] An error was thrown when executing task
26.03.2025 - 16:36:11 - java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.connection.Server.sendData(String, byte[])" because the return value of "net.md_5.bungee.api.connection.ProxiedPlayer.getServer()" is null
26.03.2025 - 16:36:11 - 	at me.neznamy.tab.platforms.bungeecord.BungeeTabPlayer.sendPluginMessage(BungeeTabPlayer.java:76)
26.03.2025 - 16:36:11 - 	at me.neznamy.tab.shared.task.PluginMessageEncodeTask.run(PluginMessageEncodeTask.java:27)
26.03.2025 - 16:36:11 - 	at me.neznamy.tab.shared.cpu.CaughtTask.run(CaughtTask.java:18)
26.03.2025 - 16:36:11 - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
26.03.2025 - 16:36:11 - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
26.03.2025 - 16:36:11 - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
26.03.2025 - 16:36:11 - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
26.03.2025 - 16:36:11 - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
26.03.2025 - 16:36:11 - 	at java.base/java.lang.Thread.run(Thread.java:1583)
26.03.2025 - 16:36:11 - [TAB v5.0.7] An error was thrown when executing task
```

**Comment by NEZNAMY** [comment]
I see 0.26% server thread usage by bridge. That's not the source of your lag.

**Comment by RICE0707** [comment]
However, when I did the above config operation, the MSPT problem was solved,
(And I just discovered error.log)

**Comment by NEZNAMY** [comment]
Error will be fixed, but you didn't provide evidence it's bridge causing high server thread usage.

**Comment by RICE0707** [comment]
Well, maybe I can only temporarily avoid this mspt problem by modifying the config. I also tested directly removing the tab plugin, which can also avoid the mspt problem. No offense, but I am sure that this problem is caused by the tab, but the specific reason is unknown.

**Comment by NEZNAMY** [comment]
I need clear evidence on spark to work with.

**Comment by RICE0707** [comment]
I'll report back to you when I find the problem (or someone else encounters it), thanks for the immediate response

**Comment by NEZNAMY** [comment]
Any news @RICE0707 ? So far I got nothing I can work with besides the random error I fixed.

**Comment by NEZNAMY** [comment]
Well I don't think it's fair towards me to have the second false bug report from you opened without being able to do anything about it.

**Comment by NEZNAMY** [comment]
I am unable to do anything for you with the information provided. Bridge barely even does anything and all plugin message processing is done off the main thread. I cannot imagine what could I possibly do here.

**Comment by RICE0707** [comment]
waterfall 583 / PurPur 1.20.2
5.0.7 / TAB-Bridge 6.0.1

and
```yml
header-footer:
  header:
  - '            &f/                                                      &f\            '
  - '        &7/                                                                &7\        '
  - '&f<                                                                          &f>'
  - '        &7\                                                                &7/        '
  - '            &f\                                                      &f/            '
  - '&fꆖꆗꆘ'
  - ''
  - '#cfffc0%serveronline% &8/ &f60 &8« &7%server% &8• &7全伺服 &8» #cfffc0%online% &8/ &f300'
  - ''
  footer:
  - ''
  - '#f6e0a4/menu &7開選單 &8- #f6e0a4/bs &7切分流 &8- #f6e0a4/sbt &7資訊欄 &8- #f6e0a4/discord&7加社群'
  - ''
```
