### ISSUE TITLE
Conditions assumes it is a number comparison when there is a > symbol in a placeholder

### ISSUE THREAD

**Issue by Neocky** [NEZNAMY/TAB#1503]
### Server version

Paper 1.21.5-93

### TAB version

v5.2.1

### Plugin list

Citizens, Denizen, Depenizen, Essentials, EssentialsSpawn, LevelledMobs, LuckPerms, PlaceholderAPI, TAB, Vault, WorldEdit, WorldGuard

### Describe the bug

When I try to use a placeholder in the condition section which has a `>` symbol in it, TAB returns an error:
```
[16:05:11 INFO]: [TAB] [WARN] Placeholder %sync:denizen_<player.has_flag[quests.current] used in a numeric condition returned "%sync:denizen_<player.has_flag[quests.current]" for player Neocky, which is not a valid number.
[16:05:11 INFO]: [TAB] [WARN] Placeholder %=true used in a numeric condition returned "%=true" for player Neocky, which is not a valid number.
[16:05:12 INFO]: [TAB] [WARN] Placeholder %sync:denizen_<player.has_flag[quests.current] used in a numeric condition returned "%sync:denizen_<player.has_flag[quests.current]" for player Neocky, which is not a valid number.
[16:05:12 INFO]: [TAB] [WARN] Placeholder %=true used in a numeric condition returned "%=true" for player Neocky, which is not a valid number.
```

I think TAB assumes it is a number comparison when the symbol `>` is in it, when in fact I want to use the equal to comparator `=` and compare text output. 

The placeholder is a variable from the Denizen Plugin from a PAPI placeholder bridge (Depenizen) which returns `true` or `false` and which I try to compare with the `=` operator. Here is a tab parse output:

![Image](https://github.com/user-attachments/assets/f1ebe438-7051-4ff4-a516-5fe476ce64fa)

My whole condition section in `config.yml`. Ignore the default nick part:
```yml
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
  denizen_quest_active:
    conditions:
    - '%sync:denizen_<player.has_flag[quests.current]>%=true'
```

Header of my scoreboard which has the `display-condition`:
```yml
    scoreboard_quest_active:
      title: '&6&lQuest'
      display-condition: denizen_quest_active
```

### Expected behavior

I can use the `=` operator to compare the text output from the Denizen placeholder with `true` for the condition and show a scoreboard with the `display-condition` option when the player has the flag.

### Steps to reproduce

Install the plugins: Denizen, Depenizen, TAB

Flag the player with a flag in my case `quests.current`:
`/ex flag <player> quests.current`

Check if player has flag:
```
Denizen: /ex narrate <player.has_flag[quests.current]>
TAB:     /tab parse me %sync:denizen_<player.has_flag[quests.current]>%
```

### Additional info

In the `placeholder-output-replacements` section in `config.yml` I have this config with also flags from denizen which work just fine:
```yml
placeholder-output-replacements:
  '%sync:denizen_<player.flag[lives].if_null[3]>%':
    '2': '&6%sync:denizen_<player.flag[lives].if_null[3]>%'
    '1': '&c%sync:denizen_<player.flag[lives].if_null[3]>%'
    '0': '&4%sync:denizen_<player.flag[lives].if_null[3]>%'
    else: '&a%sync:denizen_<player.flag[lives].if_null[3]>%'
```

Let me know if you need me to provide my full config, or help test anything. 
Thank you in advance. :)

### Checklist

- [x] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [x] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by Tanguygab** [comment]
I think the easiest solution would be to use either the Utils or Shorcut expansion for that
With Utils:
/papi ecloud download Utils
/papi reload
-> /plugins/PlaceholderAPI/config.yml
-> under `utils:` you should have a `shortcuts:`  section. Add something like this:
```yml
expansions:
  utils:
    shortcuts:
      flag: "%denizen_<player.has_flag[quests.current]>%"
```

Then in TAB you'd have `display-condition: "%sync:utils_shortcut_flag%=true"`
