### ISSUE TITLE
Nested animations don't work in header

### ISSUE THREAD

**Issue by treier57lol** [NEZNAMY/TAB#194]
**Server version**
PaperMC git-Paper-130 1.16.1

**Plugin version** ("latest" is not a version)
v2.8.3

**Describe the bug**
Nested animations don't work in the header but do in the footer. 

I wanted to have a rainbow color cycle on MyAnimation1, so I figured nested animations should work. It's not an advertised feature but it turns out they do. Only problem is that the animation doesn't want to work in the header but works fine in the footer regardless of positioning in either of them.

**How to reproduce**

config.yml
```
header:
    - ""
    - "%animation:rainbow%&lServer"
    - ""
    - "&7// %animation:rainbow%Welcome &r%nick%&7! &7//"
    - "&7&l Used memory: %memory-used% MB / %memory-max% MB"
    - ""
    - "%animation:MyAnimation2%"
footer:
    - "%animation:MyAnimation2%"
    - ""
    - "&8Players: &r%online%/%maxplayers% &8/ TPS: &r%tps%"
    - ""
```
animations.yml
```
MyAnimation2:
    change-interval: 100
    texts:
      - "%animation:rainbow%-&8--------------"
      - "&8-%animation:rainbow%-&8-------------"
      - "&8--%animation:rainbow%-&8------------"
      - "&8---%animation:rainbow%-&8-----------"
      - "&8----%animation:rainbow%-&8----------"
      - "&8-----%animation:rainbow%-&8---------"
      - "&8------%animation:rainbow%-&8--------"
      - "&8-------%animation:rainbow%-&8-------"
      - "&8--------%animation:rainbow%-&8------"
      - "&8---------%animation:rainbow%-&8-----"
      - "&8----------%animation:rainbow%-&8----"
      - "&8-----------%animation:rainbow%-&8---"
      - "&8------------%animation:rainbow%-&8--"
      - "&8-------------%animation:rainbow%-&8-"
      - "&8--------------%animation:rainbow%-"
      - "&8-------------%animation:rainbow%-&8-"
      - "&8------------%animation:rainbow%-&8--"
      - "&8-----------%animation:rainbow%-&8---"
      - "&8----------%animation:rainbow%-&8----"
      - "&8---------%animation:rainbow%-&8-----"
      - "&8--------%animation:rainbow%-&8------"
      - "&8-------%animation:rainbow%-&8-------"
      - "&8------%animation:rainbow%-&8--------"
      - "&8-----%animation:rainbow%-&8---------"
      - "&8----%animation:rainbow%-&8----------"
      - "&8---%animation:rainbow%-&8-----------"
      - "&8--%animation:rainbow%-&8------------"
      - "&8-%animation:rainbow%-&8-------------"
rainbow:
    change-interval: 100
    texts:
      - "&#ff0000"
      - "&#ff3f00"
      - "&#ff7f00"
      - "&#ffbf00"
      - "&#ffff00"
      - "&#bfff00"
      - "&#7fff00"
      - "&#3fff00"
      - "&#00ff00"
      - "&#00ff3f"
      - "&#00ff7f"
      - "&#00ffbf"
      - "&#00ffff"
      - "&#00bfff"
      - "&#007fff"
      - "&#003fff"
      - "&#0000ff"
      - "&#3f00ff"
      - "&#7f00ff"
      - "&#bf00ff"
      - "&#ff00ff"
      - "&#ff00bf"
      - "&#ff007f"
      - "&#ff003f"
```

**Expected behavior**
Nested animations work without issues.

**Actual behavior**
Nested animations only work properly in the footer.

**Additional info** (errors, screenshots, ...)
![tablist](https://user-images.githubusercontent.com/33978534/89690131-7b529280-d90e-11ea-840a-b994f07ca4dd.png)
