### ISSUE TITLE
[Feature Request] An extra mechanic for the "tab" and "tag" values.

### ISSUE THREAD

**Issue by Tomi010817** [NEZNAMY/TAB#216]
Hello Neznami! 
I had 2 little suggestions for this plugin, this one would consist of inheriting tab or tag values set from other groups that you own in case that your rank (with the highest priority on your defined priority tree on the config) doesn't have a tab or a tag value set, and another rank (that you also own) with less priority than the previous, has for example a tabsuffix value set, then this tabsuffix would be used for you.  A more detailed example would be:
```
  higherpriorityrank:
    tabprefix: '&aHello &r'
  lesspriorityrank:
    tabprefix: '&cBye &r'
    tabsuffix: '&6Extra'
```
So lets say that you are on both of these groups. Then your tabprefix would be '&aHello &r' and your tabsuffix '&6Extra', since there is no tabsuffix value defined on the one with higher priority. To avoid this to happen you can just add the value `tabsuffix: ''` on the rank with higher priority, and then the suffix of the other rank won't be inherited.
```
  higherpriorityrank:
    tabprefix: '&aHello &r'
    tabsuffix: ''
  lesspriorityrank:
    tabprefix: '&cBye &r'
    tabsuffix: '&6Extra'
```
In case you want to deactivate the inherit mechanic but with a name value, I think the best way would be adding `tabname: '{player}'` and {player} variable, changing to the name of the player respectively. But I'm not sure about that idea, neither I know if "%player_name%" would already work great in there. Or otherwise you can make it so if the value includes "name" and is empty, like this `tabname: ''` for example, then it would automatically replace to the player name.
