### ISSUE TITLE
support permission groups from LuckPerms

### ISSUE THREAD

**Issue by NESTOWL** [NEZNAMY/TAB#226]
`LuckPerms` does not support installation on `BungeeCord`
If `TAB` is set to `BungeeCord` it cannot see groups from it :(

Аnd therefore on `PaperMC` server `TAB` cannot see groups from` LuckPerms`
```
Groups:
   owner:
     tabprefix: 'test'
     tagprefix: 'test'
```

maybe you can do something in `TAB-BukkitBridge` so that it takes groups with `LuckPerms` and transfers them to `TAB` ?
