### ISSUE TITLE
Add more advanced methods for matching and removing placeholder strings

### ISSUE THREAD

**Issue by AfkF24** [NEZNAMY/TAB#259]
What the title suggests. Would greatly improve usability nonetheless. Here are a few examples:

```yaml
placeholders:
  remove-strings:
  - 'CONTAINS:< >' # would remove any lines containing "< >" at least once
  - 'STARTS:&8[' # removes any lines starting with "&8["
  - 'ENDS:&8]' # removes any lines ending with "&8]"
```

Cheers
