### ISSUE TITLE
Tab/tag suffix regression

### ISSUE THREAD

**Issue by pgmann** [NEZNAMY/TAB#39]
**Server version**
1.13.2

**Plugin version** ("latest" is not a version)
2.5.2

**Describe the bug**
`%vault-suffix%` seems to be using the value for `%vault-prefix%`.

**How to teproduce**
TAB config section:
```yaml
  _OTHER_:
    tabprefix: "%vault-prefix%"
    tagprefix: "%vault-prefix%"
    tabsuffix: "%vault-suffix%%afk%"
    tagsuffix: "%vault-suffix%%afk%"
    customtabname: "%essentialsnick%"
    customtagname: "%essentialsnick%"
    belowname: "&c%health%❤"
```
GroupManager group config section:
```yaml
  Dev:
    default: false
    permissions: []
    inheritance:
    - op
    info:
      prefix: '&9&lDev &9'
      build: true
      suffix: ''
```

**Expected behavior**
[groupmanager-prefix][playername][groupmanager-suffix][afk]

**Actual behavior**
![tab-suffix-bug](https://user-images.githubusercontent.com/5852501/65371966-71c22c80-dc61-11e9-81ec-766b2d9f9061.png)

**Additional info** (errors, screenshots, ...)
