### ISSUE TITLE
[Bug or Question] The settings in groups.yml don't take effect

### ISSUE THREAD

**Issue by Yurinann** [NEZNAMY/TAB#433]
**Server version**
TAB with Bungee (FlameCord https://github.com/2lstudios-mc/FlameCord/commit/43684d6535e365179f23d8c9450cc30e5ffc89e7)
Subserver version: Paper 1.17.1 397
Client version: 1.18 Fabric 0.12.6

**Plugin version** ("latest" is not a version)
3.0.1-pre1 (last commit: https://github.com/NEZNAMY/TAB/commit/473a37cb6a7cdc82a7e34258dedb3ca35da06756)

**Describe the bug**
The settings in groups.yml don't take effect.
My settings:
```
_DEFAULT_:
  tabprefix: "%UserPrefix_prefix% &r"
  tagprefix: "%UserPrefix_prefix% &r"
  tabsuffix: "%afk%"
  tagsuffix: "%afk%"
```
and there is no other setting in groups.yml that overrides `_DEFAULT_`.

**How to reproduce**
I'm not quite sure how to reproduce it correctly, but nothing I set in groups.yml works.

**Expected behavior**
It works fine.

**Actual behavior**
It is not working properly.

**Additional info** (errors, screenshots, ...)
Debug when player join:
```
[18:39:51 INFO]: [TAB DEBUG] Player join of Yurinann processed in 6ms
[18:39:51 INFO]: [TAB DEBUG] Loaded MySQL data of Yurinann
```
It looks normal.

Addendum: It is now displayed in the same way as the original, without any set content. `header` and `footer` are displayed normally.
