### ISSUE TITLE
Sorting & Second Username problem

### ISSUE THREAD

**Issue by IzziInside** [NEZNAMY/TAB#520]
### Server version

Spigot 1.18.2

### TAB version

3.1.0

### Describe the bug

1) Additional nickname above player.
![Screenshot_1343](https://user-images.githubusercontent.com/65154382/157123669-4a30aa7c-1448-49de-b559-24ed15e54b8b.jpg)
 
2) Wrong sorting but rightly setuped config.
![Screenshot_1344](https://user-images.githubusercontent.com/65154382/157123833-b84e43ff-2356-44c5-84c2-67c3b407e6fa.jpg)

### Expected behavior

1) There should be no white text with the player's nickname. 
2) It should sort correctly according to the config. 

### Steps to reproduce

1) 
- Add belowname, another to groups.yml
- Setup correctly config.yml

```
  unlimited-nametag-mode:
    enabled: true
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    space-between-lines: false
    disable-in-worlds:
    - disabledworld
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    disable-in-servers: []
```
- Restart server or reload plugin.

2)
- Add new sorting types to config.yml

```
  sorting-types:
  - "GROUPS:owner,developer,hl.helper,hl.builder,el.helper,el.builder,helper,builder,zk.helper,zk.builder,external,youtube,buddy,honey,bee,default,tester"
  - "PLACEHOLDER_HIGH_TO_LOW:%cmi_user_playtime_hoursf%"
  - "PLACEHOLDER_A_TO_Z:%player%"
  case-sensitive-sorting: true
```
- Restart server or reload plugin.

### Additional info

Everything worked normally until we switched from 1.17.1 to 1.18.2; and the only plugins we updated was CMI, NexEngine and TAB.

Also, here is the screenshot of plugins
![Screenshot_1345](https://user-images.githubusercontent.com/65154382/157124478-3ec33529-0117-4fc3-9e2b-a7efcd1f8c8c.jpg)
.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
