### ISSUE TITLE
Name disappears from TAB after two login attempts with same account

### ISSUE THREAD

**Issue by NamiUni** [NEZNAMY/TAB#524]
### Server version

1.18.1(velocity)

### TAB version

3.0.1 and 3.1.0

### Describe the bug

When I try to log in to the server with the same account, the name disappears from the TAB.

### Expected behavior

Name will not disappear from the TAB if you try to log in with the same account

```yaml
# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml
header-footer:
  enabled: true
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
  header:
  - '&eようこそ！&l&n%player%&r&eさん!'
  footer:
  - '&2もりのパーティ！'
  - '&e%server_version%をたのしめ！'
  per-server:
    server1:
      header:
      - an example of server with custom
      footer:
      - header/footer and prefix/suffix
    server2;server3:
      header:
      - This is a shared header for
      - server2 and server3
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - PLACEHOLDER_A_TO_Z:%essentials_nickname%
  case-sensitive-sorting: false
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
  unlimited-nametag-mode:
    enabled: false
yellow-number-in-tablist:
  enabled: false
  value: '%ping%'
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
global-playerlist:
  enabled: true
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&cHealth'
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds:
  - disabledworld
  disable-in-servers:
  - disabledserver
  scoreboards:
    admin:
      display-condition: permission:tab.scoreboard.admin
      title: Admin scoreboard
      lines:
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%&7/&4%maxplayers%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ''
      - '&6Server Info:'
      - '* &bTPS&7: %tps%'
      - '* &bUptime&7: &f%server_uptime%'
      - '* &bMemory&7: &f%memory-used%&7/&4%memory-max%'
      - '%animation:MyAnimation1%'
    scoreboard1:
      title: Default
      lines:
      - '%animation:MyAnimation1%'
      - '&6My Stats:'
      - '* &eKills&7: &f%statistic_player_kills%'
      - '* &eDeaths&7: &f%statistic_deaths%'
      - '* &eHealth&7: &f%health%'
      - ''
      - '&6Personal Info:'
      - '* &bRank&7: &f%rank%'
      - '* &bPing&7: &f%ping%&7ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
ping-spoof:
  enabled: false
  value: 0
placeholders:
  date-format: yyyy/MM/dd
  time-format: HH時mm分
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
  '%essentials_afk%':
    '%essentials_afk%': '&r'
    'yes': '&8'
    'no': '&r'
  '%server%':
    lobby: ロビー
    main: 生活
    res: 資源
    event: イベント
  '%griefprevention_remainingclaims%':
    '%griefprevention_remainingclaims%': なし
  '%vault_eco_balance_fixed%':
    '%vault_eco_balance_fixed%': なし
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    '%server_uptime%': 1000
    '%server_tps_1_colored%': 1000
  player:
    '%player_health%': 200
    '%player_ping%': 1000
    '%vault_prefix%': 1000
  relational:
    '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true
fix-pet-names:
  enabled: false
```

### Steps to reproduce

1. log in to the server
2. start Minecraft with the same account and try to log in to the same server.
3. login fails (of course).
4. the name of the account already logged in disappears from the TAB
5. It will appear again by re-logging in or moving from one server to another.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
