### ISSUE TITLE
Order Tab list without changing nametags

### ISSUE THREAD

**Issue by Sapu98** [NEZNAMY/TAB#578]
### Server version

FlamePaper 1.8

### TAB version

3.1.1

### Describe the bug

Hi, I'm trying to order alphabetically my tablist by turning on:
```
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  # https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Sorting-players-in-tablist
  sorting-types:
    - "PLACEHOLDER_A_TO_Z:%luckperms_prefix%"
```
This works, it reorders the tablist as I expect it to do, the problem is that when I enable `enabled: true`, all my players nametags change to a bugged nametag containing their rank prefix + their name: https://i.upload.systems/QG5slgo4, I want them to keep only their original name, is this possible? also, if I were to keep the changed nametag, how can I make it look normal? in teh screen it's trimmed.

### Expected behavior

Reording the tablist without changing players' nametags.

### Steps to reproduce

- Install TAB
- Set some prefixes with luckperms
- turn on 
scoreboard-teams:
  enabled: true
 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
