### ISSUE TITLE
Placeholders not working in bossbar

### ISSUE THREAD

**Issue by LuluxClient** [NEZNAMY/TAB#598]
### Server version

Bungeecord | paperspigot 1.18.2

### TAB version

3.1.1

### Describe the bug

Placeholders are not working in the bossbar.

### Expected behavior

They should work

### Steps to reproduce

Add this in your bossbar:
```
    boosters:
      style: "PROGRESS" 
      color: "WHITE" 
      progress: "100"
      text: "&a%player_name%"
      display-condition: '%player_name%=YourInGameName'  
      ```
  Make sure to do /papi ecloud download player and /papi reload before trying 
  

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
```
bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
  - disabledworld
  bars:
    boosters:
      style: "PROGRESS" 
      color: "WHITE" 
      progress: "100"
      text: "&a%player_name%"
      display-condition: '%player_name%=_NEZNAMY_'
```
![image](https://user-images.githubusercontent.com/6338394/168090796-d8fe1175-20e7-4141-9122-2efcc319a5ef.png)
