### ISSUE TITLE
Stay animations

### ISSUE THREAD

**Issue by SirCicle** [NEZNAMY/TAB#658]
Hi, is there a way to make a text in the animation stay for x milliseconds, if not please implement it

Example:
```
time:
  change-interval: 900
  texts:
  - '&7Time &b%time%'
  - '&7> Time &b%time% &7<'
  - '&7>> Time &b%time% &7<<'
  - '<stay=10000>&7>>> Time &b%time% &7<<<</stay>'
  - '&7Date &b%date%'
  - '&7> Date &b%date% &7<'
  - '&7>> Date &b%date% &7<<'
  - '<stay=10000>&7>>> Date &b%date% &7<<<</stay>'
```
