### ISSUE TITLE
Customtagname doesn't work

### ISSUE THREAD

**Issue by Ativ3k** [NEZNAMY/TAB#683]
### Server version

Spigot Paper 1.19.2

### TAB version

3.1.4

### Describe the bug

Customtagname not working.
I try edit with **/tab player <nick> customtagname** and **/tab group <groupname> customtagname** but in both cases it doesn't work.

groups.yml
```
_DEFAULT_:
  tabprefix: '%luckperms_prefix%'
  tagprefix: '%luckperms_prefix%'
  customtabname: '%essentialsnick%'
  customtagname: '%essentialsnick%'
  tabsuffix: '%vault-suffix%%afk%'
  tagsuffix: '%vault-suffix%%afk%'
```
unlimited-nametag-mode
``` 
unlimited-nametag-mode:
    enabled: true
```

customtabname works correctly.

### Expected behavior

above

### Steps to reproduce

above

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
