### ISSUE TITLE
[Bug] Tablist name format and nametag cannot disabled on specific server

### ISSUE THREAD

**Issue by Yurinann** [NEZNAMY/TAB#738]
### Server version

Waterfall 1.19

### TAB version

3.1.5

### Describe the bug

Tablist name format and nametag cannot disabled on specific server

### Expected behavior

If I set:
```
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: false
  disable-in-worlds:
  - world1
  disable-in-servers:
  - ThePit
```
then the server called ThePit shouldnt show the tablist name format and the nametag.

### Steps to reproduce

Step 1: Set Config
Step 2: /btab reload
Step 3: See the effect (reproduce)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
