### ISSUE TITLE
TAB Sorting issue

### ISSUE THREAD

**Issue by xHyroM** [NEZNAMY/TAB#750]
### Server version

Purpur 1850

### TAB version

3.1.5

### Describe the bug

![image](https://user-images.githubusercontent.com/56601352/204088792-f7fb32d4-0e15-4c62-bfa9-06ecb1390b0f.png)

Sometimes when someone connects it puts them completely up but after `/tab reload` everything works as it should. It also has double nametag since we use unlimited nametag mode

### Expected behavior

Works fine

### Steps to reproduce

I don't know exactly when it will happen, but just sometimes when someone joins it happens.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
![image](https://user-images.githubusercontent.com/6338394/204088941-e6b5a409-dfe4-42a0-b655-f3f711660189.png)
You definitely didn't read wiki either. Send your config.

**Comment by xHyroM** [comment]
```yml
# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  disable-in-worlds:
  - disabledworld
  header:
  - ''
  - '&#DC1C13&lRajce.pro'
  - '&fServer: &#eb4034OneBlock'
  - ''
  footer:
  - ''
  - '%animation:rainbow%&lPiňata'
  - '&f%pinataparty_current_votes%&8/&f%pinataparty_votes_needed%'
  - ''
  - '&fOnline: &#eb4034%bungee_total% &8(&#eb4034%online%&8) &8| &fPing: &#eb4034%ping%ms'
  per-world: null
tablist-name-formatting:
  enabled: true
  align-tabsuffix-on-the-right: false
  character-width-overrides: {}
  anti-override: true
  disable-in-worlds:
  - disabledworld
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: true
  anti-override: true
  sorting-types:
  - GROUPS:majitel,vedeni,developer,admin,manager,hlbuilder,hlmoderator,elbuilder,elmoderator,builder,moderator,zkbuilder,zkmoderator,hleventer,eventer,streamer,youtuber,anarchy,king,ninja,rajce,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-in-worlds:
  - disabledworld
  unlimited-nametag-mode:
    enabled: true
    use-marker-tag-for-1-8-x-clients: false
    disable-on-boats: true
    disable-in-worlds:
    - disabledworld
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    disable-in-servers: []
yellow-number-in-tablist:
  enabled: false
  value: '%ping%'
  disable-in-worlds:
  - disabledworld
belowname-objective:
  enabled: false
  number: '%health%'
  text: '&c❤'
  disable-in-worlds:
  - disabledworld
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
  - disabledworld
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds:
  - disabledworld
  scoreboards:
    admin:
      display-condition: permission:tab.scoreboard.admin
      title: Admin scoreboard
      lines:
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ' '
      - '&6Server Info:'
      - '* &bTPS&7: %tps%'
      - '* &bUptime&7: &f%server_uptime%'
      - '* &bMemory&7: &f%memory-used%&7/&4%memory-max%'
      - '%animation:MyAnimation1%'
    scoreboard1:
      title: Default
      lines:
      - '%animation:MyAnimation1%'
      - '&6My Stats:'
      - '* &eKills&7: &f%statistic_player_kills%'
      - '* &eDeaths&7: &f%statistic_deaths%'
      - '* &eHealth&7: &f%health%'
      - ' '
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&7ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
ping-spoof:
  enabled: false
  value: 0
fix-pet-names:
  enabled: false
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    true: ' &o[AFK]&r'
    false: ''
  '%essentials_nickname%':
    '%essentials_nickname%': '%player%'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  server:
    '%server_uptime%': 1000
    '%server_tps_1_colored%': 1000
    '%server_unique_joins%': 5000
  player:
    '%player_health%': 200
    '%player_ping%': 1000
    '%vault_prefix%': 1000
  relational:
    '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- majitel
- vedeni
- developer
- admin
- manager
- hlbuilder
- hlmoderator
- elbuilder
- elmoderator
- builder
- moderator
- zkbuilder
- zkmoderator
- hleventer
- eventer
- streamer
- youtuber
- anarchy
- king
- ninja
- rajce
- default
debug: false
```
