### ISSUE TITLE
TAB Not display ItemsAdder prefix when multiple LP tracks

### ISSUE THREAD

**Issue by Teyir** [NEZNAMY/TAB#751]
### Server version

paper 1.19.2

### TAB version

3.1.5 - Last build

### Describe the bug

I use ItemsAdder and I have a bug with luckperms tracks.

When we have 2 ranks tracks, we don't have the IA prefix show, ex:

![image](https://user-images.githubusercontent.com/60007549/205021860-2a1ab05d-62be-4ad0-9094-070a146c69a8.png)

We have this same issue with placeholders:
`%luckperms_prefix_element_highest_on_track_grades%`
![image](https://user-images.githubusercontent.com/60007549/205022051-a3ceca35-f003-4084-ae61-a0b090a48f47.png)

![image](https://user-images.githubusercontent.com/60007549/205022178-3de9fffe-7067-40b1-9cf0-59b83cb65c24.png)

And it's same with names:
![image](https://user-images.githubusercontent.com/60007549/205022327-1e630f28-36c1-4294-8e8d-9949e36dfc6a.png)

I use latest IA build and latest TAB build

Thank you very much !

### Expected behavior

Display IA prefix

### Steps to reproduce

groups.yml

```yaml
fondateur:
  tabprefix: '%img_rank_admin%&c '
  tagprefix: '%img_rank_admin%&c '
bras-droit:
  tabprefix: '%img_rank_brasdroit%&c '
  tagprefix: '%img_rank_brasdroit%&c '
resp-staff:
  tabprefix: '%img_rank_respstaff%&9 '
  tagprefix: '%img_rank_respstaff%&9 '
moderateur:
  tabprefix: '%img_rank_modo%&a '
  tagprefix: '%img_rank_modo%&a '
support:
  tabprefix: '%img_rank_support%&a '
  tagprefix: '%img_rank_support%&a '
helpeur:
  tabprefix: '%img_rank_helpeur%&9 '
  tagprefix: '%img_rank_helpeur%&9 '
animateur:
  tabprefix: '%img_rank_animateur%&5 '
  tagprefix: '%img_rank_animateur%&5 '
partenaire:
  tabprefix: '%img_rank_partenaire%&e '
  tagprefix: '%img_rank_partenaire%&e '
twitch:
  tabprefix: '%img_rank_twitch%&5 '
  tagprefix: '%img_rank_twitch%&5 '
youtube:
  tabprefix: '%img_rank_youtube%&f '
  tagprefix: '%img_rank_youtube%&f '
infinity:
  tabprefix: '%img_rank_infinity%&b '
  tagprefix: '%img_rank_infinity%&b '
legendary:
  tabprefix: '%img_rank_legendary%&d '
  tagprefix: '%img_rank_legendary%&d '
elite:
  tabprefix: '%img_rank_elite%&6 '
  tagprefix: '%img_rank_elite%&6 '
vip:
  tabprefix: '%img_rank_vip%&e '
  tagprefix: '%img_rank_vip%&e '

example_group:
  header:
  - This is an example of per-group header/footer
  footer:
  - applied to a group
per-world:
  world1:
    Owner:
      tabprefix: '&0&l[&a&lOwner&0&l] &a'
      tagprefix: '&2&lOwner &a'
_DEFAULT_:
  tabprefix: '%luckperms_prefix_element_highest_on_track_grades%'
  tagprefix: '%luckperms_prefix_element_highest_on_track_grades%'
  tabsuffix: ''
  tagsuffix: ''
  customtabname: '%essentialsnick%'
  customtagname: '%essentialsnick%'
```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
