### ISSUE TITLE
Proxy Toggle Commands

### ISSUE THREAD

**Issue by PanHaskins** [NEZNAMY/TAB#798]
### Server version

Flamecord 1.2.0

### TAB version

3.2.2

### Describe the bug

I haven't tried it yet with the Spigot server but with the Proxy (Bungee) server the tabbing of toggle commands such as scoreboard, bossbar, ... 

### Expected behavior

![image](https://user-images.githubusercontent.com/58113388/213790556-e75a040c-258e-4afd-a353-a7dbdee9d0e3.png)
i want this:
![image](https://user-images.githubusercontent.com/58113388/213790622-7f869ddb-5497-48a1-a565-d431beb79f42.png)
(TAB COMPLETE)

### Steps to reproduce

1. set toggle command in bossbar or scoreboard in config.yml 
```
bossbar:
  enabled: true
  toggle-command: /bar <--- THIS
  remember-toggle-choice: false
  hidden-by-default: false
  disable-in-worlds:
    - disabledworld
  disable-in-servers:
    - disabledserver
  bars:
    ServerInfo:
      style: "PROGRESS" # for 1.9+: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
      color: "%animation:barcolors%" # for 1.9+: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
      progress: "100" # in %
      text: "&fWebsite: &bwww.domain.com"
```

2. restart server
3. try use /bar. /bar used but can´t tabing 

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
