### ISSUE TITLE
Geyser bedrock players see the tab corrupted

### ISSUE THREAD

**Issue by HEMO313** [NEZNAMY/TAB#808]
### Server version

CarbonSpigot 1.8.9

### TAB version

3.2.3

### Describe the bug

so my server supports bedrock and java players bedrock via geyser i was using the tab plugin for a while for scoreboard and i play in java so the scoreboard looks like normal
![image](https://user-images.githubusercontent.com/39499245/214567195-35ba5404-aed0-4e38-b935-c64dc23ca99a.png)
but in bedrock the scoreboard looks like 
![image](https://user-images.githubusercontent.com/39499245/214567341-f66d88fc-477b-4f31-8c19-63205c5cd339.png)

### Expected behavior

```
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: true
  hidden-by-default: false
  use-numbers: false
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  disable-in-worlds:
  - disabledworld
  scoreboards:
    SPAWN:
      title: "&7&lSURVIVAL"
      lines:
      - '&7    %server_time_yyyy/MM/dd%'
      - ''
      - '&7Personal'
      - '&8▪ &fTime: &7%player_world_time_24% ⌚'
      - '&8▪ &fMoney: &7%vault_eco_balance_formatted%'
      - '&8▪ &fPing: &7%ping%'
      - ''
      - '&7Server'
      - '&8▪ &fPinata: &7%pinataparty_votes_left%'
      - '&8▪ &fClear: &7%clearlagtimer_formatted%'
      - ''
      - ' &7play.eaglemc.net'
```

### Steps to reproduce

just enable the scoreboard option and join with bedrock and you will see the scoreboard is broken

### Additional info

i'm using another plugin for scoreboard in other servers and the scoreboard looks normal in bedrock only with tab plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
