### ISSUE TITLE
Fallback legacy color are not fitting into 1.12.2 limit

### ISSUE THREAD

**Issue by dobr-bobr2** [NEZNAMY/TAB#827]
### Server version

Purpur 1.16.5

### TAB version

3.2.5

### Describe the bug

Gradient color-codes with fallback legacy color are not fitting into 1.12.2 limit while plain color-codes are.

### Expected behavior

It should fit, because it fits on protocol level.

### Steps to reproduce

This is steps I used to reproduce the issue on my prod server:
1. Join with 1.12.2.
2. Assign yourself a `creator` group.
3. Write this into `groups.yml` and reload the config:
```yaml
creator:
  tabprefix: '<#ff0000|4>&lCʀᴇᴀᴛᴏʀ</#aa0000>&r '
  tagprefix: '<#ff0000|4>&lCʀᴇᴀᴛᴏʀ</#aa0000>&r '
```
4. See that prefix is cut off.
5. Write this into `groups.yml` and reload the config:
```yaml
creator:
  tabprefix: '&4&lCʀᴇᴀᴛᴏʀ&r '
  tagprefix: '&4&lCʀᴇᴀᴛᴏʀ&r '
```
6. See that prefix is not cut off.

### First config
![2023-02-20_18 23 05](https://user-images.githubusercontent.com/121358718/220145631-89008c28-a3ba-4d64-b252-d499418d4ca4.png)
### Second config
![2023-02-20_18 23 20](https://user-images.githubusercontent.com/121358718/220145712-eb3af71f-74bb-4bb3-83ee-6b6e67bc265b.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
