### ISSUE TITLE
Bug with cross-server (global) tablist

### ISSUE THREAD

**Issue by HgeX** [NEZNAMY/TAB#87]
**Server version**: `1.14.4, Paper-234`
**Plugin version**: `v2.6.2`

**The bug**
A player can only see those players on the tablist, that are on the same server. When he connects to another server, then he'll see all the players from the previous server, and those on the current one. So basically you can see every player, if you go through every server.

**Expected behaviour**
Once a player connects, all players should appear on the tablist.

**Comment by NEZNAMY** [comment]
Are you sure you enabled the option in config ?

**Comment by HgeX** [comment]
Yeah, this is how the first line of the config looks right now: `global-playerlist: true`

**Comment by NEZNAMY** [comment]
And are you sure it's not at the end of the config too, but set to false ?

**Comment by HgeX** [comment]
```yaml
global-playerlist: true

change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true
enable-header-footer: true

nametag-refresh-interval-milliseconds: 1000
tablist-refresh-interval-milliseconds: 1000
header-footer-refresh-interval-milliseconds: 100

header:
  - '                                    '
  - '&6&lＮｕｇｇ&r&6&lｅｔ&f&lＣＲＡＦＴ'
  - '&7&owww.nugget.hu'
  - ''
  - ''
footer:
  - ''
  - '&8&l◄  &f&o&l%online%&7 &ojátékos  &8&l►'
  - ''
  - '%animation:nuggethu%'
  - ''
  
#the yellow number in tablist
#set to "" to disable
tablist-objective-value: ""

#NOT case sensitive
group-sorting-priority-list:
  - "tag"
  - "partner"
  - "vip"
  - "premium"
  - "veteran"
  - "seged"
  - "mod"
  - "admin"
  - "tulaj"

#properties: tabprefix, tabsuffix, tagprefix (in name tag), tagsuffix, customtabname (modifying the name itself), header, footer
Groups:
  tulaj:
    tabprefix: "&4 Tulaj &8&l❘ &9"
    tagprefix: "&4 Tulaj &8&l❘ &9"
    tabsuffix: " "
    tagsuffix: " "
  admin:
    tabprefix: "&c Admin &8&l❘ &9"
    tagprefix: "&c Admin &8&l❘ &9"
    tabsuffix: " "
    tagsuffix: " "
  mod:
    tabprefix: "&b Mod &8&l❘ &9"
    tagprefix: "&b Mod &8❘ &9"
    tabsuffix: " "
    tagsuffix: " "
  seged:
    tabprefix: "&b Segéd &8&l❘ &9"
    tagprefix: "&b Segéd &8❘ &9"
    tabsuffix: " "
    tagsuffix: " "
  veteran:
    tabprefix: "&6 Veterán &8&l❘ &9"
    tagprefix: "&6 Veterán &8&l❘ &9"
    tabsuffix: " "
    tagsuffix: " "
  premium:
    tabprefix: "&3 Prémium &8&l❘ &9"
    tagprefix: "&3 Prémium &8&l❘ &9"
    tabsuffix: " "
    tagsuffix: " "
  vip:
    tabprefix: "&a VIP &8&l❘ &9"
    tagprefix: "&a VIP &8&l❘ &9"
    tabsuffix: " "
    tagsuffix: " "
  partner:
    tabprefix: "&e Partner &8&l❘ &9"
    tagprefix: "&e Partner &8&l❘ &9"
    tabsuffix: " "
    tagsuffix: " "
  tag:
    tabprefix: "&f Tag &8&l❘ &9"
    tagprefix: "&f Tag &8&l❘ &9"
    tabsuffix: " "
    tagsuffix: " "
  #any other group not defined above
  _OTHER_:
    tabprefix: "&f Tag &8&l❘ &9"
    tagprefix: "&f Tag &8&l❘ &9"
    tabsuffix: " "
    tagsuffix: " "
    customtabname: ''
    customtagname: ''

#personal settings, override group settings
Users: []

#the vanilla belowname feature
#doesn't support player placeholders (rank, prefix), only server placeholders (time, date, animations) and static text
belowname:
  enabled: false
  refresh-interval: 200
  number: "%ping%"
  text: "&aPing"

#players 1.9+
enable-collision: false

#preventing players in spectator gamemode from appearing at the bottom of tablist with transparent name FOR OTHER PLAYERS
do-not-move-spectators: false
 
#list of worlds with different settings than default, other worlds will use settings from above
per-server-settings: []

#setting output of some placeholders        
placeholders:
  # %date%
  date-format: "dd.MM.yyyy"
  # %time%, pick one of these formats
  time-format: "[HH:mm:ss / h:mm a]"
  
  #if time doesn't show correctly, you can change the time it shows
  #setting to -1 will make it show 1 hours less than it does currently, 1 makes it show one hour more than currently, 0 does nothing
  time-offset: 0
  
#better output of %server%
server-aliases:
  Economy: "&eEconomy"
  survival: "&bSurvival"
  plot: "&cPlot"
  
rank-aliases:
  tulaj: "&4 Tulaj &8&l❘ "
  admin: "&c Admin &8&l❘ "
  mod: "&b Mod &8&l❘ "
  seged: "&b Segéd &8&l❘ "
  veteran: "&6 Veterán &8&l❘ "
  premium: "&3 Prémium &8&l❘ "
  vip: "&a VIP &8&l❘ "
  partner: "&e Partner &8&l❘ "
  tag: "&f Tag &8&l❘ "
  __OTHER__: "&f Tag &8&l❘ "
  
disable-features-in-servers:
  header-footer:
    - disabledserver
  tablist-names:
    - disabledserver
  nametag:
    - disabledserver
  tablist-objective:
    - disabledserver
  bossbar:
    - disabledserver
  belowname:
    - disabledserver
```
This is my entire configuration.
