### ISSUE TITLE
Blacklist for servers

### ISSUE THREAD

**Issue by HgeX** [NEZNAMY/TAB#88]
This is to do with global tablist. The config section could be something like `blocked-servers`. Players on blacklisted servers could see only themselves, and they'd be excluded from the global tablist.

**Comment by NEZNAMY** [comment]
Believe me or not, but i totally expected such thing to be requested almost immediately after the feature release.

**Comment by HgeX** [comment]
```yaml
disable-features-in-servers:
  header-footer:
    - disabledserver
  tablist-names:
    - disabledserver
  nametag:
    - disabledserver
  tablist-objective:
    - disabledserver
  bossbar:
    - disabledserver
  belowname:
    - disabledserver
```
Omg, how stupid I am... So I need `tablist-names`, right?
