### ISSUE TITLE
Spectator

### ISSUE THREAD

**Issue by Truongvv10** [NEZNAMY/TAB#890]
### Server version

1.19.4

### TAB version

3.3.2

### Describe the bug

When people are in a different server, in tablist it doesn't show them as spectators like it used to. 

It only shows them as spectator on different server when they just joined

With the new version, it only shows them as normal players.

### Expected behavior

Everyone should be in spectator mode if they are on different server

### Steps to reproduce

be on 2 different prixy servers

### Additional info

Using tab bridge 2.1.0

Configuration file for spectator
```yml
global-playerlist:
  enabled: true
  display-others-as-spectators: true
  display-vanished-players-as-spectators: false
  isolate-unlisted-servers: false
  update-latency: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - test
    - test2
    test:
    - build
    - towny
    - event
  fill-profile-key: false
  ```

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
