### ISSUE TITLE
Tab-Suffix Placeholder never refresh

### ISSUE THREAD

**Issue by Ratten-B** [NEZNAMY/TAB#899]
### Server version

Spigot 1.19.2

### TAB version

3.3.2 (newest)

### Describe the bug

We want to see wich position player have, so I add a Placeholder %player_x% and %player_z% into `tabsuffix: "..."`
groups.yml
```
survival:
  tabprefix: "&2&lS&aurvival &2"
  tabsuffix: " &8| &e%player_x% ~ %player_z% &8|&r"
  tagprefix: "&2&lS &2"
```
config.yml
```
tablist-name-formatting:
  enabled: true
scoreboard-teams:
  enabled: true
placeholders:
  register-tab-expansion: true
placeholderapi-refresh-intervals:
  default-refresh-interval: 100
  server:
    "%server_uptime%": 1000
    "%server_tps_1_colored%": 1000
  player:
    "%player_health%": 200
    "%player_ping%": 1000
    "%vault_prefix%": 1000
  relational:
    "%rel_factionsuuid_relation_color%": 500
```
    
  

### Expected behavior

It shows the cordinates but never refresh

### Steps to reproduce

* Stop Server
* Config Config.yml and Groups.yml
* Start Server
  * Show Ta
* /tab reload
  * Show Tab
  (after few seconds)
  * Show Tab
  (nothing will change)

### Additional info

Mayby i need to add the placeholder into `placeholderapi-refresh-intervals:`, so %player_x% refresh interval is 50 miliseconds

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
3.0.2? Latest?

**Comment by Ratten-B** [comment]
I'm sorry no! 3.3.2

**Comment by NEZNAMY** [comment]
Try latest build from actions.

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=aaV6p450hHQ).

**Comment by Ratten-B** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/40375939/1143c70d-cf80-4b42-9ca7-9a573014e466)

**Comment by NEZNAMY** [comment]
I copypasted the example you provided. Did you try latest build from actions?

**Comment by Ratten-B** [comment]
No i don't know hot to get the latest Build from Actions, but i use 3.3.2.jar

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/suites/13127168691/artifacts/713209594

**Comment by Ratten-B** [comment]
Thank you! I have the latest Build now i check it again

**Comment by Ratten-B** [comment]
my fault - incorrect Config configuration

**Comment by NEZNAMY** [comment]
How could that possibly be?

**Comment by Ratten-B** [comment]
I have delete my old Config.yml and now the coords are correct and refresh every time.

**Comment by Ratten-B** [comment]
I think I found the problem, only the placeholders in the prefix/suffix are reloaded if there are other placeholders in the tab.

**Comment by Ratten-B** [comment]
Yes i can reproduce this problem 
Do:
config.yml
```
header-footer:
  enabled: true
  header:
  - '%player_x% ~ %player_z%'
  - ' '
  footer:
  - ' '
  - ' '
```

groups.yml
```
_DEFAULT_:
  tabprefix: "%luckperms-prefix%"
  tabsuffix: "%luckperms-suffix% %player_x% ~ %player_z%"

  tagsuffix: "%luckperms-suffix%"
  tagprefix: "%luckperms-prefix%"
```

Now remove the placeholder in Tablist Header/footer
