### ISSUE TITLE
[TAB-Bridge][Velocity] backend Placeholder didn`t work

### ISSUE THREAD

**Issue by MelodyYuuka** [NEZNAMY/TAB#990]
### Server version

velocity-3.2.0-SNAPSHOT-260

### TAB version

4.0.3

### Describe the bug

![image](https://github.com/NEZNAMY/TAB/assets/81250368/b7f0fa9a-0bfd-46a9-8dad-08c0e086080c)
**TAB-Bridge v3.1.2 Connected, but backend Placeholder didn't work.**

**The backend server version that has been tested:**
  - git-PaperSpigot-445 (MC: 1.8.8)
  - git-Purpur-2016 (MC: 1.20.1)

### Expected behavior

show backend Placeholder

### Steps to reproduce

1. Install TAB 4.0.3 on Velocity (use legacy forwarding mode)
2. Install TAB-Bridge v3.1.2 + PlaceholderAPI-2.11.3 on backend server
3. Use whatever backend Placeholder in TAB

### Additional info

I know Velocity is not production ready, but a lot of people around me use Velocity and need your plugin.
My friends and I have been using your plugin for a long time and love it. Thank you for your work!

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform

**Comment by NEZNAMY** [comment]
%tps% is not a PAPI placeholder. Read TAB's startup log.

**Comment by MelodyYuuka** [comment]
I know Velocity is not ready for production.
Oh, It work, thank you.

Another problem, not so important:
![image](https://github.com/NEZNAMY/TAB/assets/81250368/ca656e16-9462-4486-8d8e-660e3a10a04f)
When someone logged in, into lobby server, and I was on another server, the incorrect "no network" sign appeared, but the ping worked.
After I switch servers, this flag becomes correct

**Comment by NEZNAMY** [comment]
Did you disable latency updating under global playerlist?

**Comment by MelodyYuuka** [comment]
> Did you disable latency updating under global playerlist?
Yes, it work, thank you!

One more question, not so important too:

When I converted my account to a Online account using [LimboAuth](https://github.com/Elytrium/LimboAuth) /premium

![image](https://github.com/NEZNAMY/TAB/assets/81250368/33d68fef-71c6-4092-be6d-93c381549c34)

When I logged on to the server, The **tab** displays the text of the **tag**.

![image](https://github.com/NEZNAMY/TAB/assets/81250368/5a77507c-49b2-45c4-9fe9-c3d7a73f9c6d)

After I switch servers, It became two, a tab and a tag.

```yaml
_DEFAULT_:
  tabprefix: "%luckperms-prefix% tab << "
  tagprefix: "%luckperms-prefix% tag << "
  customtabname: "%player%"
  customtagname: "%player%" # don't forget to enable unlimited nametag mode to make this one work
  tabsuffix: " %luckperms-suffix%[%server_name%]"
  tagsuffix: "%luckperms-suffix%"
```
